services:
  graalvm:
    build:
      context: .
      dockerfile: Dockerfile
    image: graalvm-rocky:local
    working_dir: /workspace
    volumes:
      - maven-repo:/root/m2
    ports:
      - "8080:8080"
    command: ["/workspace/target/spring-petclinic"]
volumes:
  maven-repo:
